version: "3"
services:
  video-processing-server:
    container_name: vp-server
    image: video-processing-server
    ports:
      - 9000:9000
    volumes:
      - ./server/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      PORT: 9000
      HOST: 0.0.0.0
      HOST_DATA_DIR: /home/ssuio/video-processing/server/data
      DATA_DIR: /data
      SQLITE_FILE: /data/vp.db
      VIDEO_DIR: /data/videos/
      TMP_DIR: /data/tmp/
      SESSION_KEY: ssuio
  video-processing-app:
    container_name: vp-app
    image: video-processing-app
    ports:
      - 8080:8080
    environment: 
      API_HOST: api.ezsofa.com
      NODE_ENV: production
