version: "3"
services:
  vysioneer-assignment:
    container_name: vysioneer-server
    image: vysioneer-assignment-server
    ports:
      - 9000:9000
    volumes:
      - ./server/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment: 
      PORT: 9000
      HOST: 0.0.0.0
      HOST_DATA_DIR: /home/ssuio/vysioneer-assignment/server/data
      DATA_DIR: /data
      SQLITE_FILE: /data/vysioneer.db
      VIDEO_DIR: /data/videos/
      TMP_DIR: /data/tmp/
      SESSION_KEY: ssuio
  vysioneer-assignment-app:
    container_name: vysioneer-app
    image: vysioneer-assignment-app
    ports:
      - 8080:8080
    environment: 
      API_HOST: api.ezsofa.com
      NODE_ENV: production  
