FORMAT: 1A

# User register [/user-service/register]

## Register a user [POST]

+ Request (application/json)

    {
        "email": "a@b.com",
        "name": "Noah Chou",
        "password": "Za#$9527"
    }

+ Response 200 (text/plain)
    ok

# User login [/user-service/login]

## User login [POST]

+ Response 200 (application/json)
    ok

# User login [/user-service/logout]

## User login [POST]

+ Response 200 (text/plain)
    ok


# User profile [/user]
User profile information.

## Retrieve a user profile [GET]

+ Response 200 (application/json)
  
    {
        "email": "a@b.com",
        "name": "Noah Chou",
        "createdTime": "2020-05-01T00:00:00Z"
    }     

## Update a profile [POST]
Update request fields.

+ Request (application/json)

        {
            "name": "Noah Chou"
        }

+ Response 200

# Video Management [/video/{id}]

## Retrieve an video detail [GET]

+ Parameters

    + id: 1 (number) - An unique identifier of the video.

+ Response 200 (application/json)

        {
            "id": "1b4423df-fce3-4718-b91f-686d679300b6",
            "name": "case A",
            "description": "",
            "size": 1024,
            "imageUrl": "https://host/abc",
            "createdTime": "2020-01-01-01T00:00:00Z"
        }

# Video Management [/video/{id}]

## Update a Message [POST]
Update a video information.

+ Parameters

    + id: 1 (string) - An unique identifier of the video.


+ Request (application/json)

        {
            "name": "case C"
        }

+ Response 200

# Video list [/videos]

## Retrieve all videos from a user [GET]

+ Response 200 (text/plain)

    [
        {
            "id": "fc9476be-f4a8-40d6-af59-0794ebe9b544",
            "name": "case A",
            "description": "",
            "date": ""
        },
        {
            "id": "1b4423df-fce3-4718-b91f-686d679300b6",
            "name": "case B",
            "description": "",
            "date": ""
        }
    ]

 {
    "link": "https://host/sharelink/fc9476be-f4a8-40d6-af59-0794ebe9b544"  
 }

# Video Link [/video-service/transfer]

## Retrieve an video detail [POST]

+ Request (application/json)

 {
    "type": "FACE_BLUR",
    "name": "face-blured.mp4",
    "description: "brain",
    "file: FileBody
 }

+ Response 200 (application/json)

# Video Link [/sharelink/{id}]

## Retrieve an video detail [GET]

+ Parameters

    + id: fc9476be-f4a8-40d6-af59-0794ebe9b544 (string) - An unique identifier of the video.

+ Response 200 (video/mp4)

# Video Link [/video-service/browse/{id}]

## Browse a video [GET]

+ Parameters

    + id: fc9476be-f4a8-40d6-af59-0794ebe9b544 (string) - An unique identifier of the video.

+ Response 200 (file)